name: Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Instalar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Escolha a versão do Python desejada

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Se houver um arquivo de dependências

    - name: Executar script Python
      run: python nome_do_script.py  # Substitua pelo nome do seu script
