name: Python application

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.x
      uses: actions/setup-python@v3
      with:
        python-version: "3.x"
    
    - name: Instalar dependências
      run: pip install requests
      
    - name: Acess Secret
      run: |
        echo "API_KEY=${{secrets.API_KEY}}" >> $GITHUB_ENV
        echo "API_URL=${{vars.API_URL}}" >> $GITHUB_ENV
        
    - name: Executar script Python
      run: python codigo.py
