name: Executar Python com API

on:
  push:
    branches:
      - main

jobs:
  run_python_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependências
        run: pip install requests

      - name: Executar script Python
        run: python script.py
